# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lichao Mou
author: lichao
email: lichao.mou@dlr.de
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lichao-mou.github.io/" # the base hostname & protocol for your site
repository: 
twitter_username: 
twitter:
  username: 
github_username:  
scholar_username: 7k8GAaEAAAAJ
orcid_username: 
linkedin_username: 
google_site_verification: 
social:
  name: Lichao Mou
  links:
    
logo: 

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  